query Representantes {
    representantes(sort: "nombre:asc") {
        id
        nombre
        profile_img {
            url
        } 
        partido {
            id
            partido_titulo
        }
        puesto
    }
}